In [1]:
import pandas as pd
from pathlib import Path

In [2]:
carpetas = {
    Path('..') / 'data' / 'closed_eye': 0,
    Path('..') / 'data' / 'open_eye': 1
}
dataset = []

In [3]:
for carpeta, etiqueta in carpetas.items():
    if carpeta.exists():
        for archivo in carpeta.iterdir():
            if archivo.suffix.lower() in ('.png', '.jpg', '.jpeg'):
                dataset.append({
                    'filepath': str(archivo),
                    'label': etiqueta
                })

In [4]:
df = pd.DataFrame(dataset)

In [5]:
df.head(5)

                                          filepath  label
0  ../data/closed_eye/s0014_03016_0_1_0_2_0_01.png      0
1  ../data/closed_eye/s0011_00631_0_0_0_0_0_01.png      0
2  ../data/closed_eye/s0012_03237_0_1_0_0_0_01.png      0
3  ../data/closed_eye/s0019_01148_0_0_0_0_0_01.png      0
4  ../data/closed_eye/s0014_00139_0_0_0_0_0_01.png      0

In [6]:
df = df.sample(frac=1, random_state=42)

In [7]:
df.head(5)

                                              filepath  label
32771    ../data/open_eye/s0011_01526_0_0_1_0_0_01.png      1
39512    ../data/open_eye/s0024_00263_0_0_1_0_0_01.png      1
43581    ../data/open_eye/s0012_08448_0_0_1_1_0_02.png      1
2975   ../data/closed_eye/s0004_00085_0_0_0_0_0_01.png      0
3377   ../data/closed_eye/s0005_00519_0_0_0_0_0_01.png      0

In [8]:
df.to_csv('dataset.csv', index=False)